### ISSUE TITLE
Opens the .destop file in an editor instead of running it

### ISSUE THREAD

**Issue by dfaust** [dfaust/plasma-applet-popup-launcher#8]
This bug has been reported twice, but I wasn't able to reproduce it.

The applications are executed using `Kio.KRun.openUrl` and I haven't found an alternative, yet.

**Comment by SyndromeDayna** [comment]
Maybe you should use [Kio.KRun.runUrl](https://api.kde.org/frameworks/kio/html/classKRun.html#a73cdb95167576c44fcf19f1ac0d98ecf) with mime type = "application/x-desktop" and RunFlags = RunExecutables

**Comment by dfaust** [comment]
@SyndromeDayna Thank you, but I have no idea how to get this working with QML.

I created a bug report at https://bugs.kde.org/show_bug.cgi?id=411178.

And I was able to reproduce the bug after updating KF5 to version 5.61.0.

**Comment by dfaust** [comment]
I have just released version 1.3 which includes a work-around thanks to @Alban-Boissard.

**Comment by bepaald** [comment]
~~I just installed 1.3 from here: https://www.pling.com/p/1084934/~~

~~And nothing has changed, the .desktop files are still opened in my editor (as has happened since the update to KF5 5.61.0). Currently on KF5 5.62.0. Requesting this issue is reopened.~~

EDIT: Sorry, spoke too soon, even though I had uninstalled the old version, it's somehow mixing and matching files from the old and new versions, and occasionally claiming the widget isn't installed at all, even though I just added it from the available widgets (?).

Anyway, this is probably my setup, so please ignore this comment and forgive the noise.

**Comment by akwala** [comment]
This is happening in Kubuntu 20.04. I installed the widget from the Pling store. 

Upon selecting an item in the popup list, the corresponding *.desktop file is opened in the text editor. ~~To have the widget launch the application, the *.desktop file has to be made executable. Most *.desktop files are in /usr/share/applications and are not all consistently executable.~~ _With the latest version, *.desktop files open in the editor even if they are executable._
